### ISSUE TITLE
Update total after someones 'stemmeberedtelse' is changed

### ISSUE THREAD

**Issue by thommath** [dotkom/super-duper-fiesta#142]

**Comment by sklirg** [comment]
We're going to do this the way the old system did it.

Once an issue is opened they total amount of eligible voters is locked in as the total amount of eligible voters at that time.

This means that it's not possible to gain or loose voting eligibility during this time.

This also means that this problem is a non-issue since it'll never update during the course of an active issue. 

I added it to the maintenance milestone in case we want to revisit this later on.
